# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the port your frontend runs on within the container (e.g., 3000)
EXPOSE 3000

# Command to run your frontend application
CMD ["npm", "start"]
